### PR TITLE
Add $RERA Icon

### PR DESCRIPTION
**Pull request by dgidbaba**
0x0e8891E0E3049d148664Af30623c214d293e17F0 Icon

### CODE REVIEW

**Comment by BenTokenFinance** [comment]
Can you provide more information about this token?

**Comment by dgidbaba** [comment]
Any other specific details i need to give?

**Comment by BenTokenFinance** [comment]
Yes, I would appreciate if you can help me verify your identity. e.g. by sending a request from official email & DM me in TG for more proof. Thanks.

**Comment by dgidbaba** [comment]
Done that pls

**Comment by dgidbaba** [comment]
Waiting please!!!

**Comment by BenTokenFinance** [comment]
I found an email in the admin@benswap.finance inbox. Please check my reply. Thanks

**Comment by BenTokenFinance** [comment]
Logo is added after confirmation. Congrats

**Comment by dgidbaba** [comment]
Thnks 🙂

**Pull request closed without merging**
