### PR TITLE
add Wenlambo token

### PR DESCRIPTION
**Pull request by wenlambotoken**

### CODE REVIEW

**Comment by BenTokenFinance** [comment]
Please separate into two PRs. Token info needs stricter review so please check in logo first

**Comment by BenTokenFinance** [comment]
https://docs.benswap.cash/features/amm

**Comment by wenlambotoken** [comment]
> Please separate into two PRs. Token info needs stricter review so please check in logo first

I did it!

**Comment by wenlambotoken** [comment]
> Please separate into two PRs. Token info needs stricter review so please check in logo first

i will close this pr, made a new one.

**Pull request closed without merging**
